apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all-logs-flow
  namespace: logging
spec:
  filters:
    - record_transformer:
        enable_ruby: true
        record:
          app_group: '${ (record["kubernetes"]["labels"]["name"] rescue nil) || (record["kubernetes"]["labels"]["app"] rescue nil) || record["kubernetes"]["namespace_name"] || "unknown" }'
  globalOutputRefs:
    - elasticsearch-vm