apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all-logs-flow
  namespace: logging
spec:
  filters:
    - record_transformer:
        enable_ruby: true
        record:
          app_group: ${ record["kubernetes"]["labels"]["app"] || record["kubernetes"]["namespace_name"] }
    - rewrite_tag_filter:
        rules:
          - name: app_group
            regexp: ^(.+)$
            replacement: $1
  globalOutputRefs:
    - elasticsearch-vm