apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - logging-infra.yaml
  - es-cluster-output.yaml
  - cluster-flow.yaml

# Kustomize can automatically apply the 'logging' namespace to everything
namespace: logging