apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: redis-flow
  namespace: redis
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        key_name: log
        # Note: 'parse' is singular here and replaces 'parsers'
        parse:
          type: regexp
          expression: '/^(?<time>\d+:\w+ \d+ \d+:\d+:\d+\.\d+) (?<level>[.*#]) (?<message>.*)$/'
          time_format: "%d %b %Y %H:%M:%S.%L"
  match:
    - select: {}
  localOutputRefs:
    - es-output