apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: redis-flow
  namespace: redis
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        parse_static: true
        key_name: log
        parsers:
          - type: regexp
            # This helps parse standard Redis log formats
            expression: /^(?<time>\d+:\w+ \d+ \d+:\d+:\d+\.\d+) (?<level>[.*#]) (?<message>.*)$/
            time_format: "%d %b %Y %H:%M:%S.%L"
  match:
    - select: {}
  localOutputRefs:
    - es-output