# relok8s image hints file
# This file makes this Helm Chart relocatable by relok8s
# More info here https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes
#
# haproxy chart

# haproxy image
- "{{.image.registry}}/{{.image.repository}}:{{.image.tag}}"

