apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: guestbook-flow
  namespace: guestbook
spec:
  filters:
    - record_transformer:
        enable_ruby: true
        record:
          app_group: "guestbook"
  match:
     - select:
         labels:
           app: guestbook-ui
  globalOutputRefs:
    - elasticsearch-vm
