apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: guestbook-flow
  namespace: guestbook
spec:
  filters:
    - tag_normaliser: {}
    # - parser:
    #     remove_key_name_field: true
    #     reserve_data: true
    #     parse:
    #       type: nginx
    - record_transformer:
        enable_ruby: true
        record:
          app_group: "guestbook"  
      
  match:
     - select:
         labels:
           app: guestbook-ui
  globalOutputRefs:
    - elasticsearch-vm
