apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-kafka-cluster
  namespace: argocd 
  # This annotation is helpful to ensure ArgoCD doesn't try to sync
  # before the necessary Custom Resource Definitions (CRDs) are fully registered.
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    # 1. REPLACE with the URL of your Git repository containing kafka-cluster.yaml
    repoURL: https://github.com/solaris2006/argocd-example-apps-c.git
    targetRevision: HEAD
    # 2. REPLACE with the path to your kafka-cluster.yaml file
    path: kafka 
  destination:
    server: https://kubernetes.default.svc 
    namespace: kafka # Namespace where the Kafka cluster will be built
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Ensure the target namespace for Kafka exists
      - CreateNamespace=true
      # Useful flag when dealing with CRDs and external operators
      - Replace=true
      - SkipDryRunOnMissingResource=true