# --- 1. PersistentVolumeClaim (PVC) ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    app: redis
spec:
  # Define the access mode needed by Redis
  accessModes:
    - ReadWriteOnce # Can be mounted by one node read-write
  resources:
    requests:
      storage: 1Gi