# --- Redis Commander Service (NodePort or LoadBalancer) ---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
  labels:
    app: redis-commander
spec:
  # Use LoadBalancer for k3d access (as mapped for ArgoCD)
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081 # Target the container port
    protocol: TCP
  selector:
    app: redis-commander